### ISSUE TITLE
Proxy content type header lacks charset value

### ISSUE THREAD

**Issue by storytracer** [currencybot/open-exchange-rates#11]
By accident I noticed that https://raw.github.com/currencybot/open-exchange-rates/master/currencies.json looks like this:

`"STD": "São Tomé and Príncipe Dobra",`

while http://openexchangerates.org/currencies.json looks like this

`"STD": "SÃ£o TomÃ© and PrÃ­ncipe Dobra",`

I figured out that

`Content-Type: application/json`

should rather be

`Content-Type: application/json; charset=utf-8`

**Comment by wjcrowcroft** [comment]
Good catch, thanks. Doesn't seem to be a problem for me, but I've updated the code with the `charset` anyway to be sure.

**Comment by storytracer** [comment]
Did you already enable the change on the proxy? I still get `Content-Type: application/json` as response.

**Comment by wjcrowcroft** [comment]
Ah yeah the old PHP script that served the files appended the charset to the header, but now when you access the proxy, you're just directly hitting the files, so the content type is automatically `application/json`

Do you know what I can put in .htaccess to serve JSON files with `charset=utf-8` content type?

**Comment by wjcrowcroft** [comment]
Think I fixed it, have a check now. It sends `Content-Type:application/json; charset=utf-8`, but seems to only send that when the file is not cached. Not sure if that's something I need to change, or if it's all fine - .htaccess was never a massive strong point for me!

FYI, I added these lines:

```
AddType application/json .json
AddDefaultCharset utf-8
AddCharset utf-8 .json
```

**Comment by storytracer** [comment]
Yep, looks all good now. Nicely done!
